version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: leaflet-geosearch
    versions:
    - 3.3.0
    - 3.3.1
  - dependency-name: faker
    versions:
    - 5.5.0
    - 5.5.1
